### PR TITLE
Imagej/imagej ops2/optional params

### LINKED ISSUE #110: Optional parameters don't work outside of scijava-ops-engine
Declaring parameters `@Optional` outside of the `scijava-ops-engine` component leads to `IllegalAccessError`.

For example, `DefaultMeanFilter` should have an optional `OutOfBoundsFactory` parameter:
```java
public void compute(final RandomAccessibleInterval<T> input, final Shape inputNeighborhoodShape,
		@Optional OutOfBoundsFactory<T, RandomAccessibleInterval<T>> outOfBoundsFactory,
		final RandomAccessibleInterval<V> output) {
	if (outOfBoundsFactory == null)
		outOfBoundsFactory = new OutOfBoundsBorderFactory<>();
	RandomAccessibleInterval<T> extended = Views.interval((Views.extend(input, outOfBoundsFactory)), input);
	mapper.compute(extended, inputNeighborhoodShape, statsOp, output);
}
```

But attempting to match this with:
```java
ops.op("filter.mean").input(img, shape).output(output).compute();
```
produces the following exception:
```
java.lang.IllegalAccessError: class org.scijava.ops.engine.reduce.DefaultMeanFilterReduction1RandomAccessibleInterval_Shape_RandomAccessibleInterval_RandomAccessibleInterval (in module org.scijava.ops.engine) cannot access class net.imagej.ops2.filter.mean.DefaultMeanFilter (in module net.imagej.ops2) because module org.scijava.ops.engine does not read module net.imagej.ops2

	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.reduce.DefaultMeanFilterReduction1RandomAccessibleInterval_Shape_RandomAccessibleInterval_RandomAccessibleInterval.compute(DefaultMeanFilterReduction1RandomAccessibleInterval_Shape_RandomAccessibleInterval_RandomAccessibleInterval.java)
	at org.scijava.ops.engine@0-SNAPSHOT/org.scijava.ops.engine.matcher.impl.OpWrappers$Computer2OpWrapper$1GenericTypedComputer2.compute(OpWrappers.java:844)
	at org.scijava.ops.api@0-SNAPSHOT/org.scijava.ops.api.OpBuilder$Arity2_IV_OV.compute(OpBuilder.java:1020)
```

This means that `scijava.ops.engine` would need a `requires xxxx` on any package using `@Optional` in *its own `module-info.java`, which of course would be cyclic and also non-extensible.

### PR DESCRIPTION
**Pull request by hinerm**
Fixes Op reduction outside of the scijava engine and updates ops to take advantage of Optional parameters.

Closes https://github.com/scijava/scijava/issues/110

### CODE REVIEW

**Comment by hinerm** [comment]
@gselzer I know this is your own work. I'm happy with it. Just wanted to check if you have any objections to these op modifications.

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/coloc/icq/LiICQ.java [hunk 1]
```diff
@@ -62,12 +63,12 @@
 	 *
 	 * @param image1
 	 * @param image2
-	 * @param mean1
-	 * @param mean2
+	 * @param mean1 (required = false)
+	 * @param mean2 (required = false)
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/coloc/icq/LiICQ.java:67]: @hinerm does this actually do anything structural? I can't remember.

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/deconvolve/RichardsonLucyF.java [hunk 2]
```diff
@@ -182,22 +184,27 @@ private void computeFilter(final RandomAccessibleInterval<I> input,
...
 	@Override
 	public RandomAccessibleInterval<O> apply(RandomAccessibleInterval<I> input, RandomAccessibleInterval<K> kernel,
-			long[] borderSize, OutOfBoundsFactory<I, RandomAccessibleInterval<I>> obfInput,
-			OutOfBoundsFactory<K, RandomAccessibleInterval<K>> obfKernel, O outType, C complexType,
-			Integer maxIterations, Boolean nonCirculant, Boolean accelerate, ExecutorService es) {
+			O outType, C complexType, Integer maxIterations,
+			Boolean nonCirculant, Boolean accelerate, ExecutorService executorService,
+			@Optional long[] borderSize,
+			@Optional OutOfBoundsFactory<I, RandomAccessibleInterval<I>> obfInput,
+			@Optional OutOfBoundsFactory<K, RandomAccessibleInterval<K>> obfKernel)
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/deconvolve/RichardsonLucyF.java:204]: This parameter is unused, should we just remove it?

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/deconvolve/RichardsonLucyTVF.java [hunk 3]
```diff
@@ -172,23 +174,27 @@ public void computeFilter(final RandomAccessibleInterval<I> input, final RandomA
...
 	@Override
 	public RandomAccessibleInterval<O> apply(RandomAccessibleInterval<I> input, RandomAccessibleInterval<K> kernel,
-			long[] borderSize, OutOfBoundsFactory<I, RandomAccessibleInterval<I>> obfInput,
-			OutOfBoundsFactory<K, RandomAccessibleInterval<K>> obfKernel, O outType, C complexType,
-			Integer maxIterations, Boolean nonCirculant, Boolean accelerate, Float regularizationFactor, ExecutorService es) {
+			O outType, C complexType, Integer maxIterations,
+			Boolean nonCirculant, Boolean accelerate, Float regularizationFactor,
+			ExecutorService executorService, @Optional long[] borderSize,
+			@Optional OutOfBoundsFactory<I, RandomAccessibleInterval<I>> obfInput,
+			@Optional OutOfBoundsFactory<K, RandomAccessibleInterval<K>> obfKernel)
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/deconvolve/RichardsonLucyTVF.java:194]: This parameter is unused, can we remove it?

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveFFTC.java [hunk 4]
```diff
@@ -93,11 +93,11 @@ public void compute(RandomAccessibleInterval<I> in, RandomAccessibleInterval<K>
 	/**
 	 * TODO
 	 *
-	 * @param input
+	 * @param in
 	 * @param kernel
 	 * @param fftInput
 	 * @param fftKernel
-	 * @param executorService
+	 * @param es
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveFFTC.java]: Can we use Optional parameters to combine this Op with the one above?

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveFFTF.java [hunk 5]
```diff
@@ -83,19 +84,20 @@
...
 	@Override
 	public RandomAccessibleInterval<O> apply(final RandomAccessibleInterval<I> input,
-			final RandomAccessibleInterval<K> kernel, final long[] borderSize,
-			final OutOfBoundsFactory<I, RandomAccessibleInterval<I>> obfInput,
+			final RandomAccessibleInterval<K> kernel,
 			final O outType, final C complexType,
-			final ExecutorService es) {
+			final ExecutorService executorService,
+			@Optional final long[] borderSize,
+			@Optional OutOfBoundsFactory<I, RandomAccessibleInterval<I>> obfInput) {
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveFFTF.java:100]: I know that the Op that uses this parameter does a `null` check, but we can't assume that will always be the case - someone could write another Op that gets matched instead, where this OOBF is not required. It's probably not going to happen here, but I don't want to get in the habit of doing this.

I think we have to require that any Op declaring Optional parameters **has** to populate the nulls - it can't let them propagate down into dependencies.

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveFFTF.java [hunk 6]
```diff
@@ -181,10 +183,10 @@ public Computers.Arity2<RandomAccessibleInterval<I>, RandomAccessibleInterval<K>
...
 	 */
 	@Override
-		public RandomAccessibleInterval<FloatType> apply(RandomAccessibleInterval<I> t, RandomAccessibleInterval<K> u, ExecutorService es) {
+		public RandomAccessibleInterval<FloatType> apply(RandomAccessibleInterval<I> input, RandomAccessibleInterval<K> kernel, ExecutorService executorService) {
 			OutOfBoundsFactory<I, RandomAccessibleInterval<I>> obfInput = new OutOfBoundsConstantValueFactory<>(Util
-					.getTypeFromInterval(t).createVariable());
-			return convolveOp.apply(t, u, null, obfInput, new FloatType(), new ComplexFloatType(), es);
+					.getTypeFromInterval(input).createVariable());
+			return convolveOp.apply(input, kernel, new FloatType(), new ComplexFloatType(), executorService, null, obfInput);
 		}
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveFFTF.java:194]: Do you think it's worth keeping this Op? We could just make more parameters Optional above.

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveNaiveF.java [hunk 7]
```diff
@@ -92,22 +93,21 @@ public RandomAccessibleInterval<O> createOutput(RandomAccessibleInterval<I> inpu
...
+	 * @param obf (required = false)
+	 * @param outType (required = false)
 	 * @return the output
 	 */
 	@Override
 	public RandomAccessibleInterval<O> apply(final RandomAccessibleInterval<I> input,
-			final RandomAccessibleInterval<K> kernel, OutOfBoundsFactory<I, RandomAccessibleInterval<I>> obf,
-			final O outType) {
+			final RandomAccessibleInterval<K> kernel, @Optional OutOfBoundsFactory<I, RandomAccessibleInterval<I>> obf,
+			final @Optional O outType) {
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveNaiveF.java]: `outType` shouldn't be optional - it defines the element type of the output image, which could cause some nasty `ClassCastException`s down the line.

But, from a purely raw-type perspective this behavior sucks :frowning:. Happy to hear any suggestions you have on improving this.

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/correlate/CorrelateFFTF.java [hunk 8]
```diff
@@ -80,25 +83,29 @@
...
 	@Override
 	public RandomAccessibleInterval<O> apply(final RandomAccessibleInterval<I> input,
-			final RandomAccessibleInterval<K> kernel, final long[] borderSize,
-			final OutOfBoundsFactory<I, RandomAccessibleInterval<I>> obfInput,
-			final OutOfBoundsFactory<K, RandomAccessibleInterval<K>> obfKernel, final O outType, final C complexType,
-			final ExecutorService es) {
+			final RandomAccessibleInterval<K> kernel, final O outType, final C fftType,
+			final ExecutorService es, @Optional long[] borderSize,
+			@Optional OutOfBoundsFactory<I, RandomAccessibleInterval<I>> obfInput,
+			@Optional OutOfBoundsFactory<K, RandomAccessibleInterval<K>> obfKernel ) {
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/correlate/CorrelateFFTF.java:99]: This parameter is unused.

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/gauss/Gaussians.java [hunk 9]
```diff
@@ -54,37 +55,6 @@
...
-	 * @author Christian Dietz (University of Konstanz)
-	 * @param <T> type of input and output
-	 * @param input the input image
-	 * @param es the {@link ExecutorService}
-	 * @param sigmas the sigmas for the Gaussian
-	 * @param output the pre-allocated output image
-	 * @implNote op names='filter.gauss', priority='-100.',
-	 *           type='org.scijava.function.Computers$Arity3'
-	 */
-	public static <T extends NumericType<T> & NativeType<T>> void defaultGaussRA(
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/gauss/Gaussians.java:73]: What's the rationale for deleting this? If it doesn't hurt anything, why not leave it in?

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/median/DefaultMedianFilter.java [hunk 10]
```diff
@@ -31,11 +31,14 @@
 
 import net.imglib2.RandomAccessibleInterval;
 import net.imglib2.algorithm.neighborhood.Shape;
+import net.imglib2.outofbounds.OutOfBoundsBorderFactory;
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/median/DefaultMedianFilter.java]: Unused import

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/min/DefaultMinFilter.java [hunk 11]
```diff
@@ -31,11 +31,14 @@
 
 import net.imglib2.RandomAccessibleInterval;
 import net.imglib2.algorithm.neighborhood.Shape;
+import net.imglib2.outofbounds.OutOfBoundsBorderFactory;
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/min/DefaultMinFilter.java]: Unused import

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/mean/DefaultMeanFilter.java [hunk 12]
```diff
@@ -30,17 +30,23 @@
 package net.imagej.ops2.filter.mean;
 
 import net.imglib2.RandomAccessibleInterval;
+import net.imglib2.algorithm.neighborhood.Neighborhood;
 import net.imglib2.algorithm.neighborhood.Shape;
+import net.imglib2.outofbounds.OutOfBoundsBorderFactory;
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/mean/DefaultMeanFilter.java]: Unused import

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/max/DefaultMaxFilter.java [hunk 13]
```diff
@@ -31,11 +31,14 @@
 
 import net.imglib2.RandomAccessibleInterval;
 import net.imglib2.algorithm.neighborhood.Shape;
+import net.imglib2.outofbounds.OutOfBoundsBorderFactory;
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/max/DefaultMaxFilter.java]: Unused import

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/threshold/ApplyThresholdMethodLocal.java [hunk 14]
```diff
@@ -369,12 +371,12 @@ protected Computers.Arity1<Histogram1d<T>, T> getComputeThresholdOp() {
...
 		public void compute(final RandomAccessibleInterval<T> input,
 			final Shape inputNeighborhoodShape,
-			final OutOfBoundsFactory<T, RandomAccessibleInterval<T>> outOfBoundsFactory,
+			@Optional OutOfBoundsFactory<T, RandomAccessibleInterval<T>> outOfBoundsFactory,
 			final RandomAccessibleInterval<BitType> output)
 		{
 			if (thresholdOp == null) thresholdOp = getThresholdOp();
-			ApplyCenterAwareNeighborhoodBasedFilter.compute(input,
-				inputNeighborhoodShape, outOfBoundsFactory, thresholdOp, output);
+			applyFilterOp.compute(input, thresholdOp,
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/threshold/ApplyThresholdMethodLocal.java:381]: Can we do a `null`-check on `outOfBoundsFactory`?

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/threshold/localBernsen/LocalBernsenThreshold.java [hunk 15]
```diff
@@ -52,28 +53,31 @@
...
 	 */
 	@Override
 	public void compute(final RandomAccessibleInterval<T> input,
 		final Shape inputNeighborhoodShape, final Double contrastThreshold,
 		final Double halfMaxValue,
-		final OutOfBoundsFactory<T, RandomAccessibleInterval<T>> outOfBoundsFactory,
+		@Optional OutOfBoundsFactory<T, RandomAccessibleInterval<T>> outOfBoundsFactory,
 		final RandomAccessibleInterval<BitType> output)
 	{
 		compute(input, inputNeighborhoodShape, contrastThreshold, halfMaxValue,
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/threshold/localBernsen/LocalBernsenThreshold.java:79]: Can we null-check `outOfBoundsFactory`?

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/threshold/localContrast/LocalContrastThreshold.java [hunk 16]
```diff
@@ -51,32 +52,24 @@
 	@OpDependency(name = "threshold.localContrast")
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/threshold/localContrast/LocalContrastThreshold.java:53]: You know, it seems to me like all of these `LocalXThreshold` Ops are nearly the same - can we make an abstract class which
1. `null`-checks the `outOfBoundsFactory`
2. Calls some private method `getThresholdOp`, which returns a field that is an `OpDependency` in all implementations.
3. Calls `applyFilterOp`
What do you think of this?

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/threshold/localPhansalkar/ComputeLocalPhansalkarThreshold.java [hunk 17]
```diff
@@ -90,7 +91,7 @@
 	 */
 	@Override
 	public void compute(final Iterable<T> inputNeighborhood,
-		final T inputCenterPixel, final Double k, final Double r,
+		final T inputCenterPixel, @Optional final Double k, @Optional final Double r,
```
Comment (gselzer) [inline imagej/imagej-ops2/src/main/java/net/imagej/ops2/threshold/localPhansalkar/ComputeLocalPhansalkarThreshold.java]: We could just inline the other `compute` method, looks like it's not being called anywhere?

The other method is `public static`, but it isn't being exported...

File: imagej/imagej-ops2/src/test/java/net/imagej/ops2/deconvolve/DeconvolveTest.java [hunk 18]
```diff
@@ -137,6 +141,29 @@ null, new FloatType(),
...
+						Inplaces.Arity1<RandomAccessibleInterval<FloatType>>, Computers.Arity1<RandomAccessibleInterval<FloatType>, RandomAccessibleInterval<FloatType>>, //
+						List<Inplaces.Arity1<RandomAccessibleInterval<FloatType>>>, //
+						ExecutorService, RandomAccessibleInterval<FloatType>, RandomAccessibleInterval<FloatType>>>() {},
+				new Nil[] { new Nil<RandomAccessibleInterval<FloatType>>() {},
+						new Nil<RandomAccessibleInterval<FloatType>>() {}, //
+						new Nil<RandomAccessibleInterval<ComplexFloatType>>() {}, //
+						new Nil<RandomAccessibleInterval<ComplexFloatType>>() {}, //
+						new Nil<Boolean>() {}, new Nil<Boolean>() {}, new Nil<ComplexFloatType>() {}, //
+						new Nil<Integer> () {}, new Nil<Inplaces.Arity1<RandomAccessibleInterval<FloatType>>>() {}, //
+						new Nil<Computers.Arity1<RandomAccessibleInterval<FloatType>, RandomAccessibleInterval<FloatType>>>() {}, //
```
Comment (gselzer) [inline imagej/imagej-ops2/src/test/java/net/imagej/ops2/deconvolve/DeconvolveTest.java:162]: Sigh...

File: imagej/imagej-ops2/src/test/java/net/imagej/ops2/filter/NonLinearFiltersTest.java [hunk 19]
```diff
@@ -161,7 +161,7 @@ public void testMinFilter() {
 	 */
 	@Test
 	public void testSigmaFilter() {
-		ops.op("filter.sigma").input(in, shape, oobFactory, 1.0, 0.0).output(out).compute();
+		ops.op("filter.sigma").input(in, shape, 1.0, 0.0, oobFactory).output(out).compute();
```
Comment (gselzer) [inline imagej/imagej-ops2/src/test/java/net/imagej/ops2/filter/NonLinearFiltersTest.java:184]: Might want to test with/without the optional parameter.

Comment (gselzer) [reply imagej/imagej-ops2/src/test/java/net/imagej/ops2/filter/NonLinearFiltersTest.java:184]: And the same goes for the other tests.

**Review by gselzer — CHANGES_REQUESTED** [review]
Thank you so much @hinerm!

I had a couple comments, but this is awesome!

File: imagej/imagej-ops2/src/test/java/net/imagej/ops2/deconvolve/DeconvolveTest.java (hunk 18 above)
Comment (gselzer) [reply imagej/imagej-ops2/src/test/java/net/imagej/ops2/deconvolve/DeconvolveTest.java:162]: By the way, the compiler is smart enough to infer the `specialType` if you're using `ops.op`, so you can just write 

```java
=ops.op("deconvolve.richardsonLucy", new Nil<>() {}, new Nil[] {...}, ...
```

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/coloc/icq/LiICQ.java (hunk 1 above)
Comment (hinerm) [reply imagej/imagej-ops2/src/main/java/net/imagej/ops2/coloc/icq/LiICQ.java:67]: No it doesn't do anything right now AFAIK but I liked it being documented in the javadoc.

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/deconvolve/RichardsonLucyF.java (hunk 2 above)
Comment (hinerm) [reply imagej/imagej-ops2/src/main/java/net/imagej/ops2/deconvolve/RichardsonLucyF.java:204]: My first pass was to remove it. Then I realized it is probably there intentionally to allow consistent calls for future optimization. Since it's optional anyway I decided to leave it.

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/deconvolve/RichardsonLucyTVF.java (hunk 3 above)
Comment (hinerm) [reply imagej/imagej-ops2/src/main/java/net/imagej/ops2/deconvolve/RichardsonLucyTVF.java:194]: Keeping for now.

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveFFTC.java (hunk 4 above)
Comment (hinerm) [reply imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveFFTC.java]: yep.. done

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveNaiveF.java (hunk 7 above)
Comment (hinerm) [reply imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveNaiveF.java]: whooooops! Got over-zealous.

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/correlate/CorrelateFFTF.java (hunk 8 above)
Comment (hinerm) [reply imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/correlate/CorrelateFFTF.java:99]: I know it's stupid but just keeping it for now.

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveFFTF.java (hunk 6 above)
Comment (hinerm) [reply imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/convolve/ConvolveFFTF.java:194]: I'm ok leaving it since it ties the complex and out types together.

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/gauss/Gaussians.java (hunk 9 above)
Comment (hinerm) [reply imagej/imagej-ops2/src/main/java/net/imagej/ops2/filter/gauss/Gaussians.java:73]: It does actually hurt things. See https://github.com/scijava/scijava/issues/115

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/threshold/localContrast/LocalContrastThreshold.java (hunk 16 above)
Comment (hinerm) [reply imagej/imagej-ops2/src/main/java/net/imagej/ops2/threshold/localContrast/LocalContrastThreshold.java:53]: I have a deep hatred for the threshold ops and unraveling their chain of dependencies. There already are a set of abstract classes in [ApplyThresholdMethod](https://github.com/scijava/incubator/blob/d6dc50695a38c678b1de6336868fcbe49bbb9e9f/imagej/imagej-ops2/src/main/java/net/imagej/ops2/threshold/ApplyThresholdMethod.java#L1). Maybe we could just reuse those. But I'm punting on it til "later".

File: imagej/imagej-ops2/src/main/java/net/imagej/ops2/threshold/localPhansalkar/ComputeLocalPhansalkarThreshold.java (hunk 17 above)
Comment (hinerm) [reply imagej/imagej-ops2/src/main/java/net/imagej/ops2/threshold/localPhansalkar/ComputeLocalPhansalkarThreshold.java]: Agreed

File: imagej/imagej-ops2/src/test/java/net/imagej/ops2/filter/NonLinearFiltersTest.java (hunk 19 above)
Comment (hinerm) [reply imagej/imagej-ops2/src/test/java/net/imagej/ops2/filter/NonLinearFiltersTest.java:184]: In general I had mixed feelings over testing the optional params. It is nice, though, to ensure we have things annotated correctly.

**Comment by hinerm** [comment]
@gselzer I think I addressed everything.. let me know if I missed something!
